---
newssources:
  washingtonpost:
    rss_urls:
      - https://www.washingtontimes.com/rss/headlines/news/politics
      - https://www.washingtontimes.com/rss/headlines/news/national
  nytimes:
    rss_urls:
      - https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
      - https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml
